name: Ship library
inputs:
  type:
    description: "Build type"
    required: false
    default: lite
runs:
  using: composite
  steps:
    - name: Call actual implementation
      uses: LasagnaCake/Makai/etc/gh/actions/ship-it/impl@main
      with:
        os: ${{case(runner.os == 'Windows', 'win', 'linux')}}
        env: ${{case(runner.os == 'Windows', 'msys2', 'linux')}}
        shell: ${{case(runner.os == 'Windows', 'msys2 {0}', 'bash')}}
        lite: ${{case(inputs.type == 'lite', true, false)}}
