ROOT := ../../..
include $(ROOT)/make/core.make

override prefix := $(call concat, $(prefix), game)

INCLUDES := $(INC_MAKAI)

.PHONY: debug release all
.ONESHELL:
.SHELLFLAGS = -ec

all: debug release

debug:


release:
