#! /bin/bash

get-total-time () {
	grep -o "total-time:\s*[0-9._]*" "$1" | sed -e "s/total-time:/ /g" >> output/result.flow
}

begin () {
	echo ] >> output/result.flow
}

end () {
	echo "$1 [" >> output/result.flow
}

do-python () {
	python test.perf.$1.*.py > output/result.$1.python.txt ;
}

do-lua () {
	lua test.perf.$1.*.lua > output/result.$1.lua.txt ;
}

do-breve () {
	../../../output/bin/art test.perf.$1.*.bv -S -C > output/result.$1.breve.txt ;
}

PERF_TESTS=()

do-test() {
	do-python $1 & PERF_TESTS[${#example_array[@]}]=$!
	do-lua $1 & PERF_TESTS[${#example_array[@]}]=$!
	#do-breve $1 & PERF_TESTS[${#example_array[@]}]=$!
}

mkdir -p output

echo "" > output/result.flow

rm -rf output/result*.txt
rm -rf output/result.flow

PERF_TESTS=()

echo Starting tests...

do-test 01

echo Waiting for tests to finish...

for TEST in ${PERF_TESTS[*]}; do
    wait $TEST
done

echo Generating result file...

profile () {
	begin $1
	get-total-time output/result.01.$1.txt
	end
}

#profile breve
profile lua
profile python

echo Done!