; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#include "regutil.iss"

#define MyAppName "Makai"
#define MyAppVersion "2.0"
#define MyAppPublisher "LasagnaCake"
#define MyAppURL "https://github.com/LasagnaCake/Makai"

#define SourceDir "../output"
#define OutDir "../output/package/win"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{DF7EE3B0-0D53-4FAF-B9E4-EB1D2ACCAFEA}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DefaultGroupName={#MyAppName}
DisableProgramGroupPage=yes
LicenseFile="../LICENSE"
; Uncomment the following line to run in non administrative install mode (install for current user only).
PrivilegesRequired=lowest
SolidCompression=yes
WizardStyle=modern zircon
OutputDir={#OutDir}
OutputBaseFilename=makai-aio-win64
PrivilegesRequiredOverridesAllowed=dialog
SetupArchitecture=x64
SetupMutex=MakaiSuperbInstallationMutexLock,Global\MakaiSuperbInstallationMutexLock
SetupIconFile=../etc/branding/logo-v1b.ico
;WizardImageFile=../etc/branding/chr-v1.png
DisableWelcomePage=no

[Types]
Name: "full"; Description: "Install everything (ART DevKit + Makai Framework + Additional Tooling)"
Name: "art_sdk"; Description: "Install what is needed for development targeting Anima Runtime"
Name: "art_env"; Description: "Install only the Anima Runtime Environment"
Name: "custom"; Description: "Custom installation"; Flags: iscustom

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Files]
Source: "{#SourceDir}/bin/anima/*"; DestDir: "{app}/bin/anima"; Flags: ignoreversion recursesubdirs createallsubdirs; Components: sdk
Source: "{#SourceDir}/bin/art.exe"; DestDir: "{app}/bin"; Flags: ignoreversion recursesubdirs createallsubdirs; Components: art
Source: "{#SourceDir}/bin/concerto.exe"; DestDir: "{app}/bin"; Flags: ignoreversion recursesubdirs createallsubdirs; Components: sdk
Source: "{#SourceDir}/bin/brevec.exe"; DestDir: "{app}/bin"; Flags: ignoreversion recursesubdirs createallsubdirs; Components: sdk
Source: "{#SourceDir}/bin/minimac.exe"; DestDir: "{app}/bin"; Flags: ignoreversion recursesubdirs createallsubdirs; Components: sdk
Source: "{#SourceDir}/bin/packer.exe"; DestDir: "{app}/bin"; Flags: ignoreversion recursesubdirs createallsubdirs; Components: tools
Source: "{#SourceDir}/bin/d2d.exe"; DestDir: "{app}/bin"; Flags: ignoreversion recursesubdirs createallsubdirs; Components: tools
Source: "{#SourceDir}/bin/mkpg.exe"; DestDir: "{app}/bin"; Flags: ignoreversion recursesubdirs createallsubdirs; Components: tools
Source: "{#SourceDir}/include/*"; DestDir: "{app}/include"; Flags: ignoreversion recursesubdirs createallsubdirs; Components: libmakai
Source: "{#SourceDir}/lib/*"; DestDir: "{app}/lib"; Flags: ignoreversion recursesubdirs createallsubdirs; Components: libmakai
Source: "{#SourceDir}/bin/*.dll"; DestDir: "{app}/bin"; Flags: ignoreversion recursesubdirs createallsubdirs; Components: art libmakai sdk tools
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Components]
Name: "art"; Description: "Anima Runtime Environment"; Types: full art_sdk art_env
Name: "sdk"; Description: "ART Development Kit (concerto + minimac + brevec)"; Types: full art_sdk
Name: "tools"; Description: "Additional tooling (packer + d2d + mkpg)"; Types: full
Name: "libmakai"; Description: "Makai Application Framework"; Types: full
Name: "add2path"; Description: "Add to PATH"; Types: full art_sdk art_env

[Icons]
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"

[Registry]
Root: HKLM; Subkey: "SYSTEM\CurrentControlSet\Control\Session Manager\Environment"; \
  ValueType: expandsz; ValueName: "Path"; ValueData: "{olddata};{app}/bin"; \
  Check: IsPathUnregistered('{app}/bin'); Components: add2path

