name: Get environment info
inputs:
  type:
    description: "Build type"
    required: false
    default: lite
outputs:
  os:
    value: ${{case(runner.os == 'Windows', 'win', 'linux')}}
  env:
    value: ${{case(runner.os == 'Windows', 'msys2', 'linux')}}
  shell:
    value: ${{case(runner.os == 'Windows', 'msys2 {0}', 'bash')}}
  lite:
    value: ${{case(inputs.type == 'lite', '1', '0')}}
  date:
    value: ${{steps.date.output.today}}
runs:
  using: composite
  steps:
    - name: Get today's date
      id: date
      run: echo "today=$(date +%Y%m%d%H%M)" >> $GITHUB_OUTPUT
      shell: bash
    - name: Get today's date
      if: runner.os != 'Windows' && runner.os != 'Linux'
      run: echo "::error unsupported operating system [${{runner.os}}]!"
      shell: bash
