name: Ship library (Actual Implementation)
inputs:
  os:
    description: Operating system
    required: false
    default: win
  env:
    description: Compilation environment
    required: false
    default: msys2
  shell:
    description: System shell
    required: false
    default: msys2 {0}
  lite:
    description: Whether building lite version
    required: false
    default: false
runs:
  using: composite
  steps:
    - name: Prepare environment
    - uses: LasagnaCake/Makai/etc/gh/actions/setup/${{inputs.env}}@main
    - uses: actions/checkout@v4
    - name: Build library
      run: make ship-it os=${{inputs.os}} lite=${{inputs.lite}} skip-tooling=${{inputs.lite}}
      shell: ${{inputs.shell}}
    - name: Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: lib-${{inputs.os}}-${{case(inputs.lite, lite, full)}}
        path: output/${{inputs.os}}-*.zip
