name: C/C++ CI

on:
  push:
    branches: [ "the-great-refactor" ]
  pull_request:
    branches: [ "the-great-refactor" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up GCC
      uses: egor-tensin/setup-gcc@v1
      with:
        version: 13.2.0
        platform: x64
    - name: Use compilers
      env:
        CC: ${{ steps.install_cc.outputs.cc }}
        CXX: ${{ steps.install_cc.outputs.cxx }}
    - name: Start
      run: echo "Starting build..."
    - name: make debug
      run: make debug
    - name: make release
      run: make debug
