name: C/C++ CI

on:
  push:
    branches: [ "the-great-refactor" ]
  pull_request:
    branches: [ "the-great-refactor" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install compiler
      id: install_cc
      uses: rlalik/setup-cpp-compiler@master
      with:
        compiler: gcc-13.0.2
    - name: Use the compilers
      env:
        CC: ${{ steps.install_cc.outputs.cc }}
        CXX: ${{ steps.install_cc.outputs.cxx }}
    - name: Start
      run: echo "Starting build..."
    - name: make debug
      run: make debug
      env:
        CC: ${{ steps.install_cc.outputs.cc }}
        CXX: ${{ steps.install_cc.outputs.cxx }}
    - name: make release
      run: make debug
      env:
        CC: ${{ steps.install_cc.outputs.cc }}
        CXX: ${{ steps.install_cc.outputs.cxx }}
