name: C/C++ CI

on:
  push:
    branches: [ "the-great-refactor" ]
  pull_request:
    branches: [ "the-great-refactor" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make debug
      run: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
        sudo apt-get update -y
        sudo apt-get install gcc-13 g++-13
        make debug
      env:
       CC:   gcc-13
       CXX:  g++-13
    - name: make release
      run: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
        sudo apt-get update -y
        sudo apt-get install gcc-13 g++-13
        make debug
      env:
       CC:   gcc-13
       CXX:  g++-13
