name: Core Library CI

on:
  schedule:
    - cron: '30 9 * * 1-5'
#  push:
#    branches: [ "the-great-refactor" ]
#    paths: [ "**.hpp", "**.cpp", ".github/workflows", "Makefile" ]
  pull_request:
    types: [ "closed" ]
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4
    - name: Install compiler
      id: install_cc
      uses: rlalik/setup-cpp-compiler@master
      with:
        compiler: gcc-13
    - name: make debug
      run: make debug
      env:
        CC: ${{ steps.install_cc.outputs.cc }}
        CXX: ${{ steps.install_cc.outputs.cxx }}
    - name: make release
      run: make release
      env:
        CC: ${{ steps.install_cc.outputs.cc }}
        CXX: ${{ steps.install_cc.outputs.cxx }}
