name: Core Library CI

on:
  schedule:
    - cron: '30 9 * * 1'
  push:
    branches: [ "the-great-refactor" ]
  workflow_dispatch:
  workflow_call:
  pull_request:
    types: [ "closed" ]
    branches: [ "main" ]

jobs:
  install-gcc13:
    name: Install GCC-13
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v4
    - name: Install compiler
      id: install_cc
      uses: rlalik/setup-cpp-compiler@master
      with:
        compiler: gcc-13

  build-core-lib-debug:
    name: Build Core Library (DEBUG)
    runs-on: windows-2022
    needs: install-gcc13
    steps:
    - uses: actions/checkout@v4
    - name: make debug
      run: make debug
      env:
        CC: ${{ steps.install_cc.outputs.cc }}
        CXX: ${{ steps.install_cc.outputs.cxx }}
    - uses: actions/upload-artifact@master
      with:
        name: lib-debug
        path: output

  build-core-lib-release:
    name: Build Core Library (RELEASE)
    runs-on: windows-2022
    needs: install-gcc13
    steps:
    - uses: actions/checkout@v4
    - name: make release
      run: make release
      env:
        CC: ${{ steps.install_cc.outputs.cc }}
        CXX: ${{ steps.install_cc.outputs.cxx }}
    - uses: actions/upload-artifact@master
      with:
        name: lib-release
        path: output
        
  build-tests-debug:
    name: Build Tests (DEBUG)
    runs-on: windows-2022
    needs: [build-core-lib-debug]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@master
        with:
          name: lib-debug
          path: output
      - name: make tests
        run: |
          cd tests
          make debug
          cd ..
      - uses: actions/upload-artifact@master
        with:
          name: tests-debug
          path: tests/output/debug

  build-tests-release:
    name: Build Tests (RELEASE)
    runs-on: windows-2022
    needs: [build-core-lib-release]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@master
        with:
          name: lib-release
          path: output
      - name: make tests
        run: |
          cd tests
          make release
          cd ..
      - uses: actions/upload-artifact@master
        with:
          name: tests-release
          path: tests/output/release
