name: Preview Builds CI

# ...at least it's working.
# I do not want to mess with this EVER AGAIN.

on:
  schedule:
    - cron: "30 9 * * 1"
  #  push:
  #    branches: [ "!legacy-system" ]
  workflow_dispatch:
  workflow_call:
#  pull_request:
#    types: [ "closed" ]
#    branches: [ "main" ]

jobs:
  prepare-linux:
    name: Prepare Linux
    runs-on: ubuntu-latest
    steps:
      - uses: LasagnaCake/Makai/etc/gh/actions/setup/linux@main

  prepare-msys2:
    name: Prepare MSYS2
    runs-on: windows-latest
    steps:
      - uses: LasagnaCake/Makai/etc/gh/actions/setup/msys2@main

  ship-it-full-linux-x64:
    name: Ship the library (FULL ver.) (Linux)
    runs-on: ubuntu-latest
    needs: [prepare-linux]
    steps:
      - uses: LasagnaCake/Makai/etc/gh/actions/ship-it@main
        with:
          type: full

  ship-it-lite-linux-x64:
    name: Ship the library (LITE ver.) (Linux)
    runs-on: ubuntu-latest
    needs: [prepare-linux]
    steps:
      - uses: LasagnaCake/Makai/etc/gh/actions/ship-it@main
        with:
          type: lite

  ship-it-full-win-x64:
    name: Ship the library (FULL ver.) (Windows)
    runs-on: windows-latest
    needs: [prepare-msys2]
    steps:
      - uses: LasagnaCake/Makai/etc/gh/actions/ship-it@main
        with:
          type: full

  ship-it-lite-win-x64:
    name: Ship the library (LITE ver.) (Windows)
    runs-on: windows-latest
    needs: [prepare-msys2]
    steps:
      - uses: LasagnaCake/Makai/etc/gh/actions/ship-it@main
        with:
          type: lite

  publish:
    name: Publish pre-release
    needs:
      - ship-it-lite-win-x64
      - ship-it-full-win-x64
      - ship-it-lite-linux-x64
      - ship-it-full-linux-x64
    runs-on: ubuntu-latest
    steps:
      - name: Get environment info
        uses: LasagnaCake/Makai/etc/gh/actions/info@main
        id: info
      - uses: actions/download-artifact@master
        with:
          path: output
      - name: Post
        uses: softprops/action-gh-release@v2
        with:
          tag_name: preview-${{steps.info.outputs.today}}
          prerelease: true
          draft: false
          files: |
            **/*.zip
          name: Preview Snapshot ${{steps.info.outputs.today}}
          body: |
            Automatically-generated preview via GitHub action.
